name: CodeCov
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ "3.9" ]
    steps:
      - name: Checkout repository
          uses: actions/checkout@v2
          with:
            fetch-depth: 2
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.7
      - name: Generate Report
        run: |
          pip install coverage tox
          coverage run -m tox
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
